#!/bin/bash
aws ecs execute-command \
      --cluster sandbox-cluster \
      --task 138821f4a562459ab725d69af0c0ef52 \
      --container sandbox-fargate \
      --interactive \
      --command "bash"