#!/bin/bash
aws ecs execute-command \
      --cluster sandbox-cluster \
      --task 7916e530b30b445088e81ed04176e326 \
      --container sandbox-fargate \
      --interactive \
      --command "bash"